Use logger for helm output
helmfile/helmfile pull request #1585
Opened 2024-06-24 11:36 UTC by inteon

My previous PR was auto-closed: https://github.com/helmfile/helmfile/pull/1386

This PR updates all helm invocations, so the output is written to stderr via the logger only.
Only when templating, we write directly to stdout.

This PR aims to improve the experience when using helmfile as a go library.

2024-06-24 11:37 UTC, inteon commented on test/integration/test-cases/diff-args/output/apply
> -Release "installed" does not exist. Installing it now.
These lines are now printed to stderr.

2024-06-24 11:37 UTC, inteon commented on test/integration/test-cases/skip-diff-output/output/diff-result
> -Comparing release=foo, chart=../../../charts/raw
This line is now printed to stderr.

2024-06-24 11:37 UTC, inteon commented on test/integration/test-cases/skip-diff-output/output/diff-result-live
> -Comparing release=foo, chart=../../../charts/raw
This line is now printed to stderr.

2024-06-25 00:08 UTC, yxxhero commented
@mumoshu WDYT?

2024-06-25 04:08 UTC, mumoshu requested changes
@inteon Thank you very much for your effort!

This looks almost good. Only two things:

- Can we also make the logging output configurable https://github.com/helmfile/helmfile/blob/442e8647a7d20ec71c54b9523c0a614fdc7681bc/cmd/root.go#L63 so that anyone wants logs to flow into stdout as before can configure to do so for some form of backward-compatibility
- Can we have test outputs for the combo of stdout/stderr, for example, named `apply-combined` and `apply-live-combined` and make tests to check those? The rationale is that, by moving some messages from stdout to stderr, we lose some test coverage. I hope we can keep the same degree of test coverage even after this change.

2024-06-28 15:54 UTC, inteon commented
> @inteon Thank you very much for your effort!
> 
> This looks almost good. Only two things:
> 
> * Can we also make the logging output configurable https://github.com/helmfile/helmfile/blob/442e8647a7d20ec71c54b9523c0a614fdc7681bc/cmd/root.go#L63
>    so that anyone wants logs to flow into stdout as before can configure to do so for some form of backward-compatibility
> * Can we have test outputs for the combo of stdout/stderr, for example, named `apply-combined` and `apply-live-combined` and make tests to check those? The rationale is that, by moving some messages from stdout to stderr, we lose some test coverage. I hope we can keep the same degree of test coverage even after this change.



> @inteon Thank you very much for your effort!
> 
> This looks almost good. Only two things:
> 
> * Can we also make the logging output configurable https://github.com/helmfile/helmfile/blob/442e8647a7d20ec71c54b9523c0a614fdc7681bc/cmd/root.go#L63
>    so that anyone wants logs to flow into stdout as before can configure to do so for some form of backward-compatibility
> * Can we have test outputs for the combo of stdout/stderr, for example, named `apply-combined` and `apply-live-combined` and make tests to check those? The rationale is that, by moving some messages from stdout to stderr, we lose some test coverage. I hope we can keep the same degree of test coverage even after this change.



> @inteon Thank you very much for your effort!
> 
> This looks almost good. Only two things:
> 
> * Can we also make the logging output configurable https://github.com/helmfile/helmfile/blob/442e8647a7d20ec71c54b9523c0a614fdc7681bc/cmd/root.go#L63
>    so that anyone wants logs to flow into stdout as before can configure to do so for some form of backward-compatibility
> * Can we have test outputs for the combo of stdout/stderr, for example, named `apply-combined` and `apply-live-combined` and make tests to check those? The rationale is that, by moving some messages from stdout to stderr, we lose some test coverage. I hope we can keep the same degree of test coverage even after this change.

@mumoshu I applied both suggested changes.

2024-06-29 04:03 UTC, yxxhero approved these changes
LGMT

2024-06-29 04:06 UTC, yxxhero commented
@mumoshu

2024-07-04 04:53 UTC, mumoshu approved these changes
LGTM. Thank you so much for your amazing work!

2024-07-04 04:53 UTC, merged